# Generated by Django 4.1.13 on 2024-09-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TBSApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routes",
            name="d_station_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="routes",
            name="s_station_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
