# Generated by Django 4.1.13 on 2024-09-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TBSApp", "0002_routes_d_station_code_routes_s_station_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ManyToManyField(related_name="bookings", to="TBSApp.routes"),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        related_name="bookings", to="TBSApp.userregister"
                    ),
                ),
            ],
        ),
    ]
