# Generated by Django 4.1.13 on 2024-09-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TBSApp", "0003_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(default="Successfully", max_length=255),
        ),
    ]
