# Generated by Django 4.1.13 on 2024-09-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TBSApp", "0005_alter_userregister_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="userregister", name="image",),
    ]
