# Generated by Django 4.1.13 on 2024-09-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TBSApp", "0006_remove_userregister_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="route",
            field=models.ManyToManyField(
                related_name="Train_number", to="TBSApp.routes"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ManyToManyField(
                related_name="user_name", to="TBSApp.userregister"
            ),
        ),
    ]
